name: sc_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.6
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_bloc: ^8.1.6
  get_it: ^8.0.1
  go_router: ^14.2.8

dev_dependencies:
  flutter_dotenv: ^5.2.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - .env
